In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from os import replace

from smacv2.env import StarCraft2Env
import numpy as np
from absl import logging
import time

from smacv2.env.starcraft2.wrapper import StarCraftCapabilityEnvWrapper

logging.set_verbosity(logging.DEBUG)

def main():

    distribution_config = {
        "n_units": 5,
        "n_enemies": 5,
        "team_gen": {
            "dist_type": "weighted_teams",
            "unit_types": ["marine", "marauder", "medivac"],
            "exception_unit_types": ["medivac"],
            "weights": [0.45, 0.45, 0.1],
            "observe": True,
        },
        "start_positions": {
            "dist_type": "surrounded_and_reflect",
            "p": 0.5,
            "n_enemies": 5,
            "map_x": 32,
            "map_y": 32,
        },
    }
    env = StarCraftCapabilityEnvWrapper(
        capability_config=distribution_config,
        map_name="10gen_terran",
        debug=True,
        conic_fov=False,
        obs_own_pos=True,
        use_unit_ranges=True,
        min_attack_range=2,
    )

    env_info = env.get_env_info()

    n_actions = env_info["n_actions"]
    n_agents = env_info["n_agents"]

    n_episodes = 10

    print("Training episodes")
    for e in range(n_episodes):
        env.reset()
        terminated = False
        episode_reward = 0

        while not terminated:
            obs = env.get_obs()
            state = env.get_state()
            # env.render()  # Uncomment for rendering

            actions = []
            for agent_id in range(n_agents):
                avail_actions = env.get_avail_agent_actions(agent_id)
                avail_actions_ind = np.nonzero(avail_actions)[0]
                action = np.random.choice(avail_actions_ind)
                actions.append(action)

            reward, terminated, _ = env.step(actions)
            time.sleep(0.15)
            episode_reward += reward
        print("Total reward in episode {} = {}".format(e, episode_reward))

if __name__ == "__main__":
    main()

INFO:absl:Launching SC2: D:\games\StarCraft II\Versions/Base92440\SC2_x64.exe -listen 127.0.0.1 -port 50768 -dataDir D:\games\StarCraft II\ -tempDir C:\Users\REM2\AppData\Local\Temp\sc-tiw2s5t9\ -displayMode 0 -windowwidth 1920 -windowheight 1200 -windowx 50 -windowy 50
INFO:absl:Connecting to: ws://127.0.0.1:50768/sc2api, attempt: 0, running: True


Training episodes


INFO:absl:Connecting to: ws://127.0.0.1:50768/sc2api, attempt: 1, running: True
DEBUG:absl:Attack Probabilities: None
DEBUG:absl:Health Levels: None
DEBUG:absl:Unit 1 is 2008, x = 4.509765625, y = 22.804931640625
DEBUG:absl:Unit 2 is 2008, x = 7.591796875, y = 29.240478515625
DEBUG:absl:Unit 3 is 2008, x = 9.815673828125, y = 24.65234375
DEBUG:absl:Unit 4 is 2009, x = 6.354248046875, y = 29.6875
DEBUG:absl:Unit 5 is 2009, x = 12.251220703125, y = 15.763916015625
DEBUG:absl:*********************Started Episode 0**********************
DEBUG:absl:------------------------Obs Agent: 1------------------------
DEBUG:absl:Avail. actions [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [0. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 1.          0.7135487  -0.30820313 -0.6435547   1.          0.
   1.          0.        ]
 [ 1.          0.50

Total reward in episode 0 = 1.2587412587412588


DEBUG:absl:------------------------Obs Agent: 0------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 1.          0.4960183  -0.06923828 -0.49116212  1.          1.
   0.          0.        ]]
DEBUG:absl:Own feats [1.         0.12905884 0.43017578 0.         1.         0.        ]
DEBUG:absl:------------------------Obs Agent: 4------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 1 = 1.6223776223776225


DEBUG:absl:------------------------Obs Agent: 4------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 1.          0.19895242  0.         -0.19895242  1.          0.
   1.          0.        ]
 [ 1.          0.10227273  0.          0.10227273  1.          0.
   1.          0.        ]
 [ 1.          0.14073618  0.09667969 -0.10227273  1.          0.
   1.          0.        ]
 [ 1.          0.16827303 -0.15858044  0.05628551  1.          1.
   0.          0.        ]]
DEBUG:absl:Own feats [1.  0.5 0.5 0.  0.  1. ]
DEBUG:absl:------------------------Obs Agent: 0------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0.

Total reward in episode 2 = 2.6351207386363633


DEBUG:absl:------------------------Obs Agent: 2------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 1.          0.09735832 -0.09705946  0.00762261  1.          0.
   1.          0.        ]
 [ 1.          0.2526824   0.13720703 -0.21218532  1.          0.
   1.          0.        ]
 [ 1.          0.07643897  0.02992079  0.07033963  1.          1.
   0.          0.        ]
 [ 1.          0.11057635 -0.00745985 -0.11032443  1.          1.
   0.          0.        ]]
DEBUG:absl:Own feats [1.         0.49656677 0.53230286 1.         0.         0.        ]
DEBUG:absl:------------------------Obs Agent: 0------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 3 = 3.160839160839161


DEBUG:absl:------------------------Obs Agent: 2------------------------
DEBUG:absl:Avail. actions [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [0. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 1.          0.24100274  0.23464626 -0.0549859   1.          0.
   0.          1.        ]]
DEBUG:absl:Own feats [1.         0.25801086 0.9161911  1.         0.         0.        ]
DEBUG:absl:------------------------Obs Agent: 4------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 4 = 1.6223776223776223


DEBUG:absl:------------------------Obs Agent: 1------------------------
DEBUG:absl:Avail. actions [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]
DEBUG:absl:Move feats [0. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0.        0.        0.        0.        0.        0.        0.
  0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.       ]
 [1.        0.5368408 0.5368408 0.        0.848     0.        1.
  0.       ]]
DEBUG:absl:Ally feats [[ 1.          0.6911565  -0.6904541  -0.03115234  1.          0.
   1.          0.        ]
 [ 1.          0.9264848   0.09636231 -0.92146     1.          0.
   1.          0.        ]
 [ 1.          0.84163874 -0.75615233 -0.3695801   1.          1.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]
DEBUG:absl:Own feats [1

Total reward in episode 5 = 3.440559440559441


DEBUG:absl:------------------------Obs Agent: 0------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 1.          0.24331897  0.10634766 -0.21884766  1.          0.
   1.          0.        ]
 [ 1.          0.10634766  0.10634766  0.          1.          0.
   1.          0.        ]
 [ 1.          0.10652547 -0.00615234  0.10634766  1.          0.
   1.          0.        ]
 [ 1.          0.21269532  0.21269532  0.          1.          0.
   1.          0.        ]]
DEBUG:absl:Own feats [1.         0.46676636 0.5        0.         1.         0.        ]
DEBUG:absl:------------------------Obs Agent: 3------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 6 = 3.720279720279721


DEBUG:absl:------------------------Obs Agent: 0------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 0.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 1.          0.9696462   0.00141059 -0.9696452   1.          0.
   0.          1.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]
DEBUG:absl:Own feats [1.         0.07226562 0.49145508 1.         0.         0.        ]
DEBUG:absl:------------------------Obs Agent: 2------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 7 = 0.8044689685314685


DEBUG:absl:------------------------Obs Agent: 1------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.44845632 0.341333   0.29086915 0.8666667  1.
  0.         0.        ]
 [1.         0.36124143 0.27941895 0.22895508 1.         0.
  1.         0.        ]]
DEBUG:absl:Ally feats [[ 1.          0.10799871 -0.06069336 -0.08933105  1.          0.
   1.          0.        ]
 [ 1.          0.0982748  -0.00126953  0.0982666   0.51111114  1.
   0.          0.        ]
 [ 1.          0.08759287  0.07683106 -0.04206543  1.          1.
   0.          0.        ]
 [ 1.          0.1507333   0.14924316 -0.02114258  1.          1.
   0.          0

Total reward in episode 8 = 6.545454545454545


DEBUG:absl:------------------------Obs Agent: 2------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feats [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
DEBUG:absl:Ally feats [[ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 1.          0.52415836  0.27533638 -0.4460178   1.          0.
   1.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.        ]]
DEBUG:absl:Own feats [1.         0.32255554 0.41645813 1.         0.         0.        ]
DEBUG:absl:------------------------Obs Agent: 1------------------------
DEBUG:absl:Avail. actions [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
DEBUG:absl:Move feats [1. 1. 1. 1.]
DEBUG:absl:Enemy feat

Total reward in episode 9 = 1.118881118881119


In [3]:
import os
import sys
import inspect
from pettingzoo import test
from smacv2.env.pettingzoo import StarCraft2PZEnv as sc2
import pickle

current_dir = os.path.dirname(
    os.path.abspath(inspect.getfile(inspect.currentframe()))
)
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)


if __name__ == "__main__":
    env = sc2.env(map_name="corridor")
    test.api_test(env)
    # test.parallel_api_test(sc2_v0.parallel_env()) # does not pass it due to
    # illegal actions test.seed_test(sc2_v0.env, 50) # not required, sc2 env
    # only allows reseeding at initialization

    recreated_env = pickle.loads(pickle.dumps(env))
    test.api_test(recreated_env)

ImportError: cannot import name 'from_parallel_wrapper' from 'pettingzoo.utils.conversions' (d:\softwares\anaconda3\envs\myrl\Lib\site-packages\pettingzoo\utils\conversions.py)

In [4]:
from smacv2.env.starcraft2.maps import smac_maps
from pysc2 import maps as pysc2_maps
from smacv2.env.pettingzoo import StarCraft2PZEnv as sc2
import pytest
from pettingzoo import test
import pickle

smac_map_registry = smac_maps.get_smac_map_registry()
all_maps = pysc2_maps.get_maps()
map_names = []
for map_name in smac_map_registry.keys():
    map_class = all_maps[map_name]
    if map_class.path:
        map_names.append(map_name)


@pytest.mark.parametrize(("map_name"), map_names)
def test_env(map_name):
    env = sc2.env(map_name=map_name)
    test.api_test(env)
    # test.parallel_api_test(sc2_v0.parallel_env()) # does not pass it due to
    # illegal actions test.seed_test(sc2.env, 50) # not required, sc2 env only
    # allows reseeding at initialization
    test.render_test(env)

    recreated_env = pickle.loads(pickle.dumps(env))
    test.api_test(recreated_env)

ImportError: cannot import name 'from_parallel_wrapper' from 'pettingzoo.utils.conversions' (d:\softwares\anaconda3\envs\myrl\Lib\site-packages\pettingzoo\utils\conversions.py)